config/routes.rb
SchemaDocSampleApp::Application.routes.draw do
  resources :loans

  resources :toys

  resources :children

  resources :parents

  root :to => "welcome#index"

end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :parent
  has_many :toys
  has_many :loans
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :child
  belongs_to :toy
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :children
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  belongs_to :child
  has_many :loans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  # GET /children
  # GET /children.xml
  def index
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @children }
    end
  end

  # GET /children/1
  # GET /children/1.xml
  def show
    @child = Child.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @child }
    end
  end

  # GET /children/new
  # GET /children/new.xml
  def new
    @child = Child.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @child }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
  end

  # POST /children
  # POST /children.xml
  def create
    @child = Child.new(params[:child])

    respond_to do |format|
      if @child.save
        format.html { redirect_to(@child, :notice => 'Child was successfully created.') }
        format.xml  { render :xml => @child, :status => :created, :location => @child }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @child.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.xml
  def update
    @child = Child.find(params[:id])

    respond_to do |format|
      if @child.update_attributes(params[:child])
        format.html { redirect_to(@child, :notice => 'Child was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @child.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.xml
  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    respond_to do |format|
      format.html { redirect_to(children_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  # GET /loans
  # GET /loans.xml
  def index
    @loans = Loan.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @loans }
    end
  end

  # GET /loans/1
  # GET /loans/1.xml
  def show
    @loan = Loan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @loan }
    end
  end

  # GET /loans/new
  # GET /loans/new.xml
  def new
    @loan = Loan.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @loan }
    end
  end

  # GET /loans/1/edit
  def edit
    @loan = Loan.find(params[:id])
  end

  # POST /loans
  # POST /loans.xml
  def create
    @loan = Loan.new(params[:loan])

    respond_to do |format|
      if @loan.save
        format.html { redirect_to(@loan, :notice => 'Loan was successfully created.') }
        format.xml  { render :xml => @loan, :status => :created, :location => @loan }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @loan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /loans/1
  # PUT /loans/1.xml
  def update
    @loan = Loan.find(params[:id])

    respond_to do |format|
      if @loan.update_attributes(params[:loan])
        format.html { redirect_to(@loan, :notice => 'Loan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @loan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.xml
  def destroy
    @loan = Loan.find(params[:id])
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to(loans_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  # GET /parents
  # GET /parents.xml
  def index
    @parents = Parent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parents }
    end
  end

  # GET /parents/1
  # GET /parents/1.xml
  def show
    @parent = Parent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @parent }
    end
  end

  # GET /parents/new
  # GET /parents/new.xml
  def new
    @parent = Parent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @parent }
    end
  end

  # GET /parents/1/edit
  def edit
    @parent = Parent.find(params[:id])
  end

  # POST /parents
  # POST /parents.xml
  def create
    @parent = Parent.new(params[:parent])

    respond_to do |format|
      if @parent.save
        format.html { redirect_to(@parent, :notice => 'Parent was successfully created.') }
        format.xml  { render :xml => @parent, :status => :created, :location => @parent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @parent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parents/1
  # PUT /parents/1.xml
  def update
    @parent = Parent.find(params[:id])

    respond_to do |format|
      if @parent.update_attributes(params[:parent])
        format.html { redirect_to(@parent, :notice => 'Parent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @parent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.xml
  def destroy
    @parent = Parent.find(params[:id])
    @parent.destroy

    respond_to do |format|
      format.html { redirect_to(parents_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  # GET /toys
  # GET /toys.xml
  def index
    @toys = Toy.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @toys }
    end
  end

  # GET /toys/1
  # GET /toys/1.xml
  def show
    @toy = Toy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @toy }
    end
  end

  # GET /toys/new
  # GET /toys/new.xml
  def new
    @toy = Toy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @toy }
    end
  end

  # GET /toys/1/edit
  def edit
    @toy = Toy.find(params[:id])
  end

  # POST /toys
  # POST /toys.xml
  def create
    @toy = Toy.new(params[:toy])

    respond_to do |format|
      if @toy.save
        format.html { redirect_to(@toy, :notice => 'Toy was successfully created.') }
        format.xml  { render :xml => @toy, :status => :created, :location => @toy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @toy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /toys/1
  # PUT /toys/1.xml
  def update
    @toy = Toy.find(params[:id])

    respond_to do |format|
      if @toy.update_attributes(params[:toy])
        format.html { redirect_to(@toy, :notice => 'Toy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @toy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.xml
  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy

    respond_to do |format|
      format.html { redirect_to(toys_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/children/_form.html.haml
- form_for(@child) do |f|
  
  - if @child.errors.any?
    #errorExplanation
      %h2= t('activerecord.errors.messages.child.invalid_record')
      %ul
      - @child.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :parent_id
    %br
    = f.select :parent_id, Parent.all.collect {|c| [c.name, c.id]}
  .field
    = f.label :name
    %br
    = f.text_field :name

  .actions
    = f.submit I18n.t('submit')

app/views/children/edit.html.haml
%h1
  = t('child.edit.title')

= render 'form'

== #{ link_to t('show'), @child } | #{ link_to t('back'), children_path }

app/views/children/index.html.haml
%h1 
  =t('children.index.title')

%table
  %thead
    %tr
      %th 
        =t('activerecord.attributes.child.parent_id')
      %th 
        =t('activerecord.attributes.child.name')
      %th{ :colspan => 3 }
  
  %tbody
    - for child in @children
      %tr{ :class => cycle(:odd, :even) }
        %td= link_to child.parent.name, parent_path(child.parent)
        %td= child.name
        %td= link_to t('show'), child
        %td= link_to t('edit'), edit_child_path(child)
        %td= link_to t('destroy'), child, :confirm => I18n.t('confirm_delete'), :method => :delete

%br
= link_to t('child.new'), new_child_path

app/views/children/new.html.haml
%h1 
  =t('child.new')

= render 'form'

= link_to t('back'), children_path

app/views/children/show.html.haml
%p
  %strong t('activerecord.attributes.child.parent_id')
  = @child.parent_id
%p
  %strong t('activerecord.attributes.child.name')
  = @child.name

== #{ link_to t('edit'), edit_child_path(@child) } | #{ link_to t('back'), children_path }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchemaDocSampleApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loans/_form.html.haml
- form_for(@loan) do |f|
  
  - if @loan.errors.any?
    #errorExplanation
      %h2= t('activerecord.errors.messages.loan.invalid_record')
      %ul
      - @loan.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :toy_id
    %br
    = f.text_field :toy_id
  .field
    = f.label :child_id
    %br
    = f.text_field :child_id
  .field
    = f.label :loaned_at
    %br
    = f.datetime_select :loaned_at
  .field
    = f.label :expected_back_at
    %br
    = f.datetime_select :expected_back_at

  .actions
    = f.submit I18n.t('submit')

app/views/loans/edit.html.haml
%h1
  = t('loan.edit.title')

= render 'form'

== #{ link_to t('show'), @loan } | #{ link_to t('back'), loans_path }

app/views/loans/index.html.haml
%h1 
  =t('loans.index.title')

%table
  %thead
    %tr
      %th 
        =t('activerecord.attributes.loan.toy_id')
      %th 
        =t('activerecord.attributes.loan.child_id')
      %th 
        =t('activerecord.attributes.loan.loaned_at')
      %th 
        =t('activerecord.attributes.loan.expected_back_at')
      %th{ :colspan => 3 }
  
  %tbody
    - for loan in @loans
      %tr{ :class => cycle(:odd, :even) }
        %td= loan.toy_id
        %td= loan.child_id
        %td= loan.loaned_at
        %td= loan.expected_back_at
        %td= link_to t('show'), loan
        %td= link_to t('edit'), edit_loan_path(loan)
        %td= link_to t('destroy'), loan, :confirm => I18n.t('confirm_delete'), :method => :delete

%br
= link_to t('loan.new'), new_loan_path

app/views/loans/new.html.haml
%h1 
  =t('loan.new')

= render 'form'

= link_to t('back'), loans_path

app/views/loans/show.html.haml
%p
  %strong t('activerecord.attributes.loan.toy_id')
  = @loan.toy_id
%p
  %strong t('activerecord.attributes.loan.child_id')
  = @loan.child_id
%p
  %strong t('activerecord.attributes.loan.loaned_at')
  = @loan.loaned_at
%p
  %strong t('activerecord.attributes.loan.expected_back_at')
  = @loan.expected_back_at

== #{ link_to t('edit'), edit_loan_path(@loan) } | #{ link_to t('back'), loans_path }

app/views/parents/_form.html.haml
- form_for(@parent) do |f|
  
  - if @parent.errors.any?
    #errorExplanation
      %h2= t('activerecord.errors.messages.parent.invalid_record')
      %ul
      - @parent.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :email
    %br
    = f.text_field :email

  .actions
    = f.submit I18n.t('submit')

app/views/parents/edit.html.haml
%h1
  = t('parent.edit.title')

= render 'form'

== #{ link_to t('show'), @parent } | #{ link_to t('back'), parents_path }

app/views/parents/index.html.haml
%h1 
  =t('parents.index.title')

%table
  %thead
    %tr
      %th 
        =t('activerecord.attributes.parent.name')
      %th 
        =t('activerecord.attributes.parent.email')
      %th{ :colspan => 3 }
  
  %tbody
    - for parent in @parents
      %tr{ :class => cycle(:odd, :even) }
        %td= parent.name
        %td= parent.email
        %td= link_to t('show'), parent
        %td= link_to t('edit'), edit_parent_path(parent)
        %td= link_to t('destroy'), parent, :confirm => I18n.t('confirm_delete'), :method => :delete

%br
= link_to t('parent.new'), new_parent_path

app/views/parents/new.html.haml
%h1 
  =t('parent.new')

= render 'form'

= link_to t('back'), parents_path

app/views/parents/show.html.haml
%p
  %strong t('activerecord.attributes.parent.name')
  = @parent.name
%p
  %strong t('activerecord.attributes.parent.email')
  = @parent.email

== #{ link_to t('edit'), edit_parent_path(@parent) } | #{ link_to t('back'), parents_path }

app/views/toys/_form.html.haml
- form_for(@toy) do |f|
  
  - if @toy.errors.any?
    #errorExplanation
      %h2= t('activerecord.errors.messages.toy.invalid_record')
      %ul
      - @toy.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :child_id
    %br
    = f.select :child_id, Child.all.collect {|c| [c.name, c.id]}
  .field
    = f.label :name
    %br
    = f.text_field :name

  .actions
    = f.submit I18n.t('submit')

app/views/toys/edit.html.haml
%h1
  = t('toy.edit.title')

= render 'form'

== #{ link_to t('show'), @toy } | #{ link_to t('back'), toys_path }

app/views/toys/index.html.haml
%h1 
  =t('toys.index.title')

%table
  %thead
    %tr
      %th 
        =t('activerecord.attributes.toy.child_id')
      %th 
        =t('activerecord.attributes.toy.name')
      %th{ :colspan => 3 }
  
  %tbody
    - for toy in @toys
      %tr{ :class => cycle(:odd, :even) }
        %td= toy.child ? toy.child.name : "unknown"
        %td= toy.name
        %td= link_to t('show'), toy
        %td= link_to t('edit'), edit_toy_path(toy)
        %td= link_to t('destroy'), toy, :confirm => I18n.t('confirm_delete'), :method => :delete

%br
= link_to t('toy.new'), new_toy_path

app/views/toys/new.html.haml
%h1 
  =t('toy.new')

= render 'form'

= link_to t('back'), toys_path

app/views/toys/show.html.haml
%p
  %strong t('activerecord.attributes.toy.child_id')
  = @toy.child_id
%p
  %strong t('activerecord.attributes.toy.name')
  = @toy.name

== #{ link_to t('edit'), edit_toy_path(@toy) } | #{ link_to t('back'), toys_path }

app/views/welcome/index.html.haml
%body
  %h1
    These database models:
  %li
    %ul= link_to('Parents', parents_path)
    %ul= link_to('Children', children_path)
    %ul= link_to('Toys', toys_path)
    %ul= link_to('Loans', loans_path)
  %h1
    Are documented 
    = link_to('on the schema_doc page', 'schema_docs')
  %div
    